version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: miaudoquintal-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: miaudoquintal
      MYSQL_USER: miau
      MYSQL_PASSWORD: miau123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
